// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IntrinsicEventIndicators.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IntrinsicEventIndicatorsRowDto
    {
        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsRowDto
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsRowDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsRowDto
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsRowDto(string rowId, string exchange, string assetPair)
        {
            RowId = rowId;
            Exchange = exchange;
            AssetPair = assetPair;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RowId")]
        public string RowId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Exchange")]
        public string Exchange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RowId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RowId");
            }
            if (Exchange == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Exchange");
            }
            if (AssetPair == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetPair");
            }
        }
    }
}
