// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IntrinsicEventIndicators.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IntrinsicEventIndicatorsRowEdit
    {
        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsRowEdit
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsRowEdit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsRowEdit
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsRowEdit(string rowId, string pairName)
        {
            RowId = rowId;
            PairName = pairName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RowId")]
        public string RowId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PairName")]
        public string PairName { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RowId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RowId");
            }
            if (PairName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PairName");
            }
        }
    }
}
