// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IncreasticEventIndicators.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ExpectedDirectionalChange.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExpectedDirectionalChange
    {
        [EnumMember(Value = "Upward")]
        Upward,
        [EnumMember(Value = "Downward")]
        Downward
    }
    internal static class ExpectedDirectionalChangeEnumExtension
    {
        internal static string ToSerializedValue(this ExpectedDirectionalChange? value)
        {
            return value == null ? null : ((ExpectedDirectionalChange)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ExpectedDirectionalChange value)
        {
            switch( value )
            {
                case ExpectedDirectionalChange.Upward:
                    return "Upward";
                case ExpectedDirectionalChange.Downward:
                    return "Downward";
            }
            return null;
        }

        internal static ExpectedDirectionalChange? ParseExpectedDirectionalChange(this string value)
        {
            switch( value )
            {
                case "Upward":
                    return ExpectedDirectionalChange.Upward;
                case "Downward":
                    return ExpectedDirectionalChange.Downward;
            }
            return null;
        }
    }
}
