// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IncreasticEventIndicators.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IntrinsicEventIndicatorsRowPost
    {
        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsRowPost
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsRowPost()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsRowPost
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsRowPost(string exchange = default(string), string assetPair = default(string))
        {
            Exchange = exchange;
            AssetPair = assetPair;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Exchange")]
        public string Exchange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

    }
}
