// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IncreasticEventIndicators.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IntrinsicEventIndicatorsDto
    {
        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsDto
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IntrinsicEventIndicatorsDto
        /// class.
        /// </summary>
        public IntrinsicEventIndicatorsDto(IList<IntrinsicEventIndicatorsColumnDto> columns = default(IList<IntrinsicEventIndicatorsColumnDto>), IList<IntrinsicEventIndicatorsAssetPairDto> assetPairs = default(IList<IntrinsicEventIndicatorsAssetPairDto>), IList<IList<double?>> data = default(IList<IList<double?>>))
        {
            Columns = columns;
            AssetPairs = assetPairs;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Columns")]
        public IList<IntrinsicEventIndicatorsColumnDto> Columns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairs")]
        public IList<IntrinsicEventIndicatorsAssetPairDto> AssetPairs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public IList<IList<double?>> Data { get; set; }

    }
}
