// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IncreasticEventIndicators.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IntrinsicEventIndicatorsAssetPairPost
    {
        /// <summary>
        /// Initializes a new instance of the
        /// IntrinsicEventIndicatorsAssetPairPost class.
        /// </summary>
        public IntrinsicEventIndicatorsAssetPairPost()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// IntrinsicEventIndicatorsAssetPairPost class.
        /// </summary>
        public IntrinsicEventIndicatorsAssetPairPost(string assetPair = default(string))
        {
            AssetPair = assetPair;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

    }
}
