// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Lykke.Service.IntrinsicEventIndicators.Client.AutorestClient.Models;

namespace Lykke.Service.IntrinsicEventIndicators.Client.AutorestClient
{
    /// <summary>
    /// Extension methods for IntrinsicEventIndicatorsAPI.
    /// </summary>
    public static partial class IntrinsicEventIndicatorsAPIExtensions
    {
            /// <summary>
            /// Adds delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='column'>
            /// Delta to add.
            /// </param>
            public static ErrorResponse ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalPut(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsColumnPost column = default(IntrinsicEventIndicatorsColumnPost))
            {
                return operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalPutAsync(column).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='column'>
            /// Delta to add.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ErrorResponse> ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalPutAsync(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsColumnPost column = default(IntrinsicEventIndicatorsColumnPost), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalPutWithHttpMessagesAsync(column, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='columnId'>
            /// delta
            /// </param>
            public static void ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalDelete(this IIntrinsicEventIndicatorsAPI operations, string columnId = default(string))
            {
                operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalDeleteAsync(columnId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='columnId'>
            /// delta
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalDeleteAsync(this IIntrinsicEventIndicatorsAPI operations, string columnId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaexternalDeleteWithHttpMessagesAsync(columnId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Adds asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='row'>
            /// Asset pair to add.
            /// </param>
            public static ErrorResponse ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalPut(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsRowPost row = default(IntrinsicEventIndicatorsRowPost))
            {
                return operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalPutAsync(row).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='row'>
            /// Asset pair to add.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ErrorResponse> ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalPutAsync(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsRowPost row = default(IntrinsicEventIndicatorsRowPost), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalPutWithHttpMessagesAsync(row, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='rowId'>
            /// asset pair
            /// </param>
            public static void ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalDelete(this IIntrinsicEventIndicatorsAPI operations, string rowId = default(string))
            {
                operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalDeleteAsync(rowId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='rowId'>
            /// asset pair
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalDeleteAsync(this IIntrinsicEventIndicatorsAPI operations, string rowId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairexternalDeleteWithHttpMessagesAsync(rowId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Gets data.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IntrinsicEventIndicatorsDto ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdataexternalGet(this IIntrinsicEventIndicatorsAPI operations)
            {
                return operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdataexternalGetAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets data.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IntrinsicEventIndicatorsDto> ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdataexternalGetAsync(this IIntrinsicEventIndicatorsAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsdataexternalGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets runners states.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IDictionary<string, IList<RunnerStateDto>> ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesexternalGet(this IIntrinsicEventIndicatorsAPI operations)
            {
                return operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesexternalGetAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets runners states.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IDictionary<string, IList<RunnerStateDto>>> ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesexternalGetAsync(this IIntrinsicEventIndicatorsAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1ExternalIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesexternalGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object IsAlive(this IIntrinsicEventIndicatorsAPI operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> IsAliveAsync(this IIntrinsicEventIndicatorsAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Adds delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='column'>
            /// Delta to add.
            /// </param>
            public static ErrorResponse ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaPut(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsColumnPost column = default(IntrinsicEventIndicatorsColumnPost))
            {
                return operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaPutAsync(column).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='column'>
            /// Delta to add.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ErrorResponse> ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaPutAsync(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsColumnPost column = default(IntrinsicEventIndicatorsColumnPost), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaPutWithHttpMessagesAsync(column, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='columnId'>
            /// delta
            /// </param>
            public static void ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaDelete(this IIntrinsicEventIndicatorsAPI operations, string columnId = default(string))
            {
                operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaDeleteAsync(columnId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes delta.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='columnId'>
            /// delta
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaDeleteAsync(this IIntrinsicEventIndicatorsAPI operations, string columnId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdeltaDeleteWithHttpMessagesAsync(columnId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Adds asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='row'>
            /// Asset pair to add.
            /// </param>
            public static ErrorResponse ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairPut(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsRowPost row = default(IntrinsicEventIndicatorsRowPost))
            {
                return operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairPutAsync(row).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='row'>
            /// Asset pair to add.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ErrorResponse> ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairPutAsync(this IIntrinsicEventIndicatorsAPI operations, IntrinsicEventIndicatorsRowPost row = default(IntrinsicEventIndicatorsRowPost), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairPutWithHttpMessagesAsync(row, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='rowId'>
            /// asset pair
            /// </param>
            public static void ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairDelete(this IIntrinsicEventIndicatorsAPI operations, string rowId = default(string))
            {
                operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairDeleteAsync(rowId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes asset pair.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='rowId'>
            /// asset pair
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairDeleteAsync(this IIntrinsicEventIndicatorsAPI operations, string rowId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsassetpairDeleteWithHttpMessagesAsync(rowId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Gets data.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IntrinsicEventIndicatorsDto ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdataGet(this IIntrinsicEventIndicatorsAPI operations)
            {
                return operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdataGetAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets data.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IntrinsicEventIndicatorsDto> ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdataGetAsync(this IIntrinsicEventIndicatorsAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsdataGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets runners states.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IDictionary<string, IList<RunnerStateDto>> ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesGet(this IIntrinsicEventIndicatorsAPI operations)
            {
                return operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesGetAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets runners states.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IDictionary<string, IList<RunnerStateDto>>> ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesGetAsync(this IIntrinsicEventIndicatorsAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiV1LykkeIntrinsicEventIndicatorsIntrinsiceventindicatorsrunnersstatesGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
